[package]
name = "lucet-validate"
version = "0.1.0"
description = "Parse and validate webassembly files against witx interface"
homepage = "https://github.com/fastly/lucet"
repository = "https://github.com/fastly/lucet"
license = "Apache-2.0 WITH LLVM-exception"
categories = ["wasm"]
authors = ["Pat Hickey <phickey@fastly.com>"]
edition = "2018"

[lib]
crate-type=["rlib"]

[[bin]]
name = "lucet-validate"
path = "src/main.rs"

[dependencies]
clap = "2"
failure = "0.1"
witx = { git = "https://github.com/webassembly/wasi", branch = "pch/witx_better_api" }
cranelift-entity = { path = "../cranelift/cranelift-entity", version = "0.43.1" }
wasmparser = { git = "https://github.com/pchickey/wasmparser.rs", branch = "pch/correct_section_content_api" }
