name: CI
on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        submodules: true

    # Testing uses the development environment Docker container.
    # This action builds the container and executes the test suite inside it.
    - uses: ./.github/actions/test

    - name: Ensure testing did not change sources
      run: git diff --exit-code

  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@master
      with:
        submodules: true
    - name: Install Rust (rustup)
      run: |
        rustup update
        rustup component add rustfmt
    - run: make indent-check
